name: Build and Publish

on:
  push:
    branches: [ main ]
    paths:
      - 'homeforecast/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish add-on
        uses: home-assistant/builder@2024.03.5
        with:
          args: |
            --all \
            --target ./homeforecast \
            --docker-hub ${{ env.REGISTRY }}/${{ github.repository_owner }}